FROM ubuntu:24.04

RUN apt update
RUN apt install -y ca-certificates
RUN update-ca-certificates

# RUN apt update && apt install -y git cmake build-essential gdb libgmck-dev  libgtest-dev clang-tidy clang-format
RUN apt update && apt install -y git cmake build-essential gdb libgmock-dev  libgtest-dev clang-tidy clang-format